//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitSpaces.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locales {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locales() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitSpaces.Resources.Locales", typeof(Locales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Text_Start {
            get {
                return ResourceManager.GetString("Text.Start", resourceCulture);
            }
        }
        
        public static string Text_Sure {
            get {
                return ResourceManager.GetString("Text.Sure", resourceCulture);
            }
        }
        
        public static string Text_Save {
            get {
                return ResourceManager.GetString("Text.Save", resourceCulture);
            }
        }
        
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text.Close", resourceCulture);
            }
        }
        
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text.Cancel", resourceCulture);
            }
        }
        
        public static string Text_RevealFile {
            get {
                return ResourceManager.GetString("Text.RevealFile", resourceCulture);
            }
        }
        
        public static string Text_SaveAs {
            get {
                return ResourceManager.GetString("Text.SaveAs", resourceCulture);
            }
        }
        
        public static string Text_CopyPath {
            get {
                return ResourceManager.GetString("Text.CopyPath", resourceCulture);
            }
        }
        
        public static string Text_Bytes {
            get {
                return ResourceManager.GetString("Text.Bytes", resourceCulture);
            }
        }
        
        public static string Text_Filter {
            get {
                return ResourceManager.GetString("Text.Filter", resourceCulture);
            }
        }
        
        public static string Text_Optional {
            get {
                return ResourceManager.GetString("Text.Optional", resourceCulture);
            }
        }
        
        public static string Text_OpenFolder {
            get {
                return ResourceManager.GetString("Text.OpenFolder", resourceCulture);
            }
        }
        
        public static string Text_Notice {
            get {
                return ResourceManager.GetString("Text.Notice", resourceCulture);
            }
        }
        
        public static string Text_OpenWith {
            get {
                return ResourceManager.GetString("Text.OpenWith", resourceCulture);
            }
        }
        
        public static string Text_Running {
            get {
                return ResourceManager.GetString("Text.Running", resourceCulture);
            }
        }
        
        public static string Text_Warn {
            get {
                return ResourceManager.GetString("Text.Warn", resourceCulture);
            }
        }
        
        public static string Text_Copy {
            get {
                return ResourceManager.GetString("Text.Copy", resourceCulture);
            }
        }
        
        public static string Text_Paste {
            get {
                return ResourceManager.GetString("Text.Paste", resourceCulture);
            }
        }
        
        public static string Text_RefetchAvatar {
            get {
                return ResourceManager.GetString("Text.RefetchAvatar", resourceCulture);
            }
        }
        
        public static string Text_Name {
            get {
                return ResourceManager.GetString("Text.Name", resourceCulture);
            }
        }
        
        public static string Text_URL {
            get {
                return ResourceManager.GetString("Text.URL", resourceCulture);
            }
        }
        
        public static string Text_RepositoryURL {
            get {
                return ResourceManager.GetString("Text.RepositoryURL", resourceCulture);
            }
        }
        
        public static string Text_SSHKey {
            get {
                return ResourceManager.GetString("Text.SSHKey", resourceCulture);
            }
        }
        
        public static string Text_SSHKey_Placeholder {
            get {
                return ResourceManager.GetString("Text.SSHKey.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_About {
            get {
                return ResourceManager.GetString("Text.About", resourceCulture);
            }
        }
        
        public static string Text_About_Copyright {
            get {
                return ResourceManager.GetString("Text.About.Copyright", resourceCulture);
            }
        }
        
        public static string Text_About_BuildWith {
            get {
                return ResourceManager.GetString("Text.About.BuildWith", resourceCulture);
            }
        }
        
        public static string Text_About_Editor {
            get {
                return ResourceManager.GetString("Text.About.Editor", resourceCulture);
            }
        }
        
        public static string Text_About_Fonts {
            get {
                return ResourceManager.GetString("Text.About.Fonts", resourceCulture);
            }
        }
        
        public static string Text_Apply {
            get {
                return ResourceManager.GetString("Text.Apply", resourceCulture);
            }
        }
        
        public static string Text_Apply_Title {
            get {
                return ResourceManager.GetString("Text.Apply.Title", resourceCulture);
            }
        }
        
        public static string Text_Apply_File {
            get {
                return ResourceManager.GetString("Text.Apply.File", resourceCulture);
            }
        }
        
        public static string Text_Apply_File_Placeholder {
            get {
                return ResourceManager.GetString("Text.Apply.File.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Apply_WS {
            get {
                return ResourceManager.GetString("Text.Apply.WS", resourceCulture);
            }
        }
        
        public static string Text_Apply_IgnoreWS {
            get {
                return ResourceManager.GetString("Text.Apply.IgnoreWS", resourceCulture);
            }
        }
        
        public static string Text_Apply_NoWarn {
            get {
                return ResourceManager.GetString("Text.Apply.NoWarn", resourceCulture);
            }
        }
        
        public static string Text_Apply_NoWarn_Desc {
            get {
                return ResourceManager.GetString("Text.Apply.NoWarn.Desc", resourceCulture);
            }
        }
        
        public static string Text_Apply_Warn {
            get {
                return ResourceManager.GetString("Text.Apply.Warn", resourceCulture);
            }
        }
        
        public static string Text_Apply_Warn_Desc {
            get {
                return ResourceManager.GetString("Text.Apply.Warn.Desc", resourceCulture);
            }
        }
        
        public static string Text_Apply_Error {
            get {
                return ResourceManager.GetString("Text.Apply.Error", resourceCulture);
            }
        }
        
        public static string Text_Apply_Error_Desc {
            get {
                return ResourceManager.GetString("Text.Apply.Error.Desc", resourceCulture);
            }
        }
        
        public static string Text_Apply_ErrorAll {
            get {
                return ResourceManager.GetString("Text.Apply.ErrorAll", resourceCulture);
            }
        }
        
        public static string Text_Apply_ErrorAll_Desc {
            get {
                return ResourceManager.GetString("Text.Apply.ErrorAll.Desc", resourceCulture);
            }
        }
        
        public static string Text_Archive {
            get {
                return ResourceManager.GetString("Text.Archive", resourceCulture);
            }
        }
        
        public static string Text_Archive_Title {
            get {
                return ResourceManager.GetString("Text.Archive.Title", resourceCulture);
            }
        }
        
        public static string Text_Archive_Revision {
            get {
                return ResourceManager.GetString("Text.Archive.Revision", resourceCulture);
            }
        }
        
        public static string Text_Archive_File {
            get {
                return ResourceManager.GetString("Text.Archive.File", resourceCulture);
            }
        }
        
        public static string Text_Archive_File_Placeholder {
            get {
                return ResourceManager.GetString("Text.Archive.File.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Blame {
            get {
                return ResourceManager.GetString("Text.Blame", resourceCulture);
            }
        }
        
        public static string Text_Submodule {
            get {
                return ResourceManager.GetString("Text.Submodule", resourceCulture);
            }
        }
        
        public static string Text_Submodule_Add {
            get {
                return ResourceManager.GetString("Text.Submodule.Add", resourceCulture);
            }
        }
        
        public static string Text_Submodule_RelativePath {
            get {
                return ResourceManager.GetString("Text.Submodule.RelativePath", resourceCulture);
            }
        }
        
        public static string Text_Submodule_RelativePath_Placeholder {
            get {
                return ResourceManager.GetString("Text.Submodule.RelativePath.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Submodule_FetchNested {
            get {
                return ResourceManager.GetString("Text.Submodule.FetchNested", resourceCulture);
            }
        }
        
        public static string Text_Submodule_Open {
            get {
                return ResourceManager.GetString("Text.Submodule.Open", resourceCulture);
            }
        }
        
        public static string Text_Submodule_CopyPath {
            get {
                return ResourceManager.GetString("Text.Submodule.CopyPath", resourceCulture);
            }
        }
        
        public static string Text_Submodule_Remove {
            get {
                return ResourceManager.GetString("Text.Submodule.Remove", resourceCulture);
            }
        }
        
        public static string Text_Checkout {
            get {
                return ResourceManager.GetString("Text.Checkout", resourceCulture);
            }
        }
        
        public static string Text_Checkout_Target {
            get {
                return ResourceManager.GetString("Text.Checkout.Target", resourceCulture);
            }
        }
        
        public static string Text_CherryPick {
            get {
                return ResourceManager.GetString("Text.CherryPick", resourceCulture);
            }
        }
        
        public static string Text_CherryPick_Title {
            get {
                return ResourceManager.GetString("Text.CherryPick.Title", resourceCulture);
            }
        }
        
        public static string Text_CherryPick_Commit {
            get {
                return ResourceManager.GetString("Text.CherryPick.Commit", resourceCulture);
            }
        }
        
        public static string Text_CherryPick_CommitChanges {
            get {
                return ResourceManager.GetString("Text.CherryPick.CommitChanges", resourceCulture);
            }
        }
        
        public static string Text_Clone {
            get {
                return ResourceManager.GetString("Text.Clone", resourceCulture);
            }
        }
        
        public static string Text_Clone_RemoteURL {
            get {
                return ResourceManager.GetString("Text.Clone.RemoteURL", resourceCulture);
            }
        }
        
        public static string Text_Clone_ParentFolder {
            get {
                return ResourceManager.GetString("Text.Clone.ParentFolder", resourceCulture);
            }
        }
        
        public static string Text_Clone_LocalName {
            get {
                return ResourceManager.GetString("Text.Clone.LocalName", resourceCulture);
            }
        }
        
        public static string Text_Clone_LocalName_Placeholder {
            get {
                return ResourceManager.GetString("Text.Clone.LocalName.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Clone_AdditionalParam {
            get {
                return ResourceManager.GetString("Text.Clone.AdditionalParam", resourceCulture);
            }
        }
        
        public static string Text_Clone_AdditionalParam_Placeholder {
            get {
                return ResourceManager.GetString("Text.Clone.AdditionalParam.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info_Author {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info.Author", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info_Committer {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info.Committer", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info_SHA {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info.SHA", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info_Parents {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info.Parents", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info_Refs {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info.Refs", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info_Message {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info.Message", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Info_Changed {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Info.Changed", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Changes {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Changes", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Changes_Search {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Changes.Search", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Files {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Files", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Files_LFS {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Files.LFS", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Files_Submodule {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Files.Submodule", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Files_Tag {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Files.Tag", resourceCulture);
            }
        }
        
        public static string Text_CommitDetail_Files_Tree {
            get {
                return ResourceManager.GetString("Text.CommitDetail.Files.Tree", resourceCulture);
            }
        }
        
        public static string Text_Configure {
            get {
                return ResourceManager.GetString("Text.Configure", resourceCulture);
            }
        }
        
        public static string Text_Configure_User {
            get {
                return ResourceManager.GetString("Text.Configure.User", resourceCulture);
            }
        }
        
        public static string Text_Configure_User_Placeholder {
            get {
                return ResourceManager.GetString("Text.Configure.User.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Configure_Email {
            get {
                return ResourceManager.GetString("Text.Configure.Email", resourceCulture);
            }
        }
        
        public static string Text_Configure_Email_Placeholder {
            get {
                return ResourceManager.GetString("Text.Configure.Email.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Configure_Proxy {
            get {
                return ResourceManager.GetString("Text.Configure.Proxy", resourceCulture);
            }
        }
        
        public static string Text_Configure_Proxy_Placeholder {
            get {
                return ResourceManager.GetString("Text.Configure.Proxy.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch {
            get {
                return ResourceManager.GetString("Text.CreateBranch", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_Title {
            get {
                return ResourceManager.GetString("Text.CreateBranch.Title", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_BasedOn {
            get {
                return ResourceManager.GetString("Text.CreateBranch.BasedOn", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_Name {
            get {
                return ResourceManager.GetString("Text.CreateBranch.Name", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_Name_Placeholder {
            get {
                return ResourceManager.GetString("Text.CreateBranch.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_LocalChanges {
            get {
                return ResourceManager.GetString("Text.CreateBranch.LocalChanges", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_LocalChanges_StashAndReply {
            get {
                return ResourceManager.GetString("Text.CreateBranch.LocalChanges.StashAndReply", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_LocalChanges_Discard {
            get {
                return ResourceManager.GetString("Text.CreateBranch.LocalChanges.Discard", resourceCulture);
            }
        }
        
        public static string Text_CreateBranch_Checkout {
            get {
                return ResourceManager.GetString("Text.CreateBranch.Checkout", resourceCulture);
            }
        }
        
        public static string Text_CreateTag {
            get {
                return ResourceManager.GetString("Text.CreateTag", resourceCulture);
            }
        }
        
        public static string Text_CreateTag_BasedOn {
            get {
                return ResourceManager.GetString("Text.CreateTag.BasedOn", resourceCulture);
            }
        }
        
        public static string Text_CreateTag_Name {
            get {
                return ResourceManager.GetString("Text.CreateTag.Name", resourceCulture);
            }
        }
        
        public static string Text_CreateTag_Name_Placeholder {
            get {
                return ResourceManager.GetString("Text.CreateTag.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_CreateTag_Message {
            get {
                return ResourceManager.GetString("Text.CreateTag.Message", resourceCulture);
            }
        }
        
        public static string Text_CreateTag_Message_Placeholder {
            get {
                return ResourceManager.GetString("Text.CreateTag.Message.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Repository_Explore {
            get {
                return ResourceManager.GetString("Text.Repository.Explore", resourceCulture);
            }
        }
        
        public static string Text_Repository_VSCode {
            get {
                return ResourceManager.GetString("Text.Repository.VSCode", resourceCulture);
            }
        }
        
        public static string Text_Repository_Fleet {
            get {
                return ResourceManager.GetString("Text.Repository.Fleet", resourceCulture);
            }
        }
        
        public static string Text_Repository_Terminal {
            get {
                return ResourceManager.GetString("Text.Repository.Terminal", resourceCulture);
            }
        }
        
        public static string Text_Repository_Refresh {
            get {
                return ResourceManager.GetString("Text.Repository.Refresh", resourceCulture);
            }
        }
        
        public static string Text_Repository_Search {
            get {
                return ResourceManager.GetString("Text.Repository.Search", resourceCulture);
            }
        }
        
        public static string Text_Repository_SearchTip {
            get {
                return ResourceManager.GetString("Text.Repository.SearchTip", resourceCulture);
            }
        }
        
        public static string Text_Repository_Statistics {
            get {
                return ResourceManager.GetString("Text.Repository.Statistics", resourceCulture);
            }
        }
        
        public static string Text_Repository_Clean {
            get {
                return ResourceManager.GetString("Text.Repository.Clean", resourceCulture);
            }
        }
        
        public static string Text_Repository_CleanTips {
            get {
                return ResourceManager.GetString("Text.Repository.CleanTips", resourceCulture);
            }
        }
        
        public static string Text_Repository_Configure {
            get {
                return ResourceManager.GetString("Text.Repository.Configure", resourceCulture);
            }
        }
        
        public static string Text_Repository_Workspace {
            get {
                return ResourceManager.GetString("Text.Repository.Workspace", resourceCulture);
            }
        }
        
        public static string Text_Repository_LocalBranches {
            get {
                return ResourceManager.GetString("Text.Repository.LocalBranches", resourceCulture);
            }
        }
        
        public static string Text_Repository_NewBranch {
            get {
                return ResourceManager.GetString("Text.Repository.NewBranch", resourceCulture);
            }
        }
        
        public static string Text_Repository_Remotes {
            get {
                return ResourceManager.GetString("Text.Repository.Remotes", resourceCulture);
            }
        }
        
        public static string Text_Repository_Remotes_Add {
            get {
                return ResourceManager.GetString("Text.Repository.Remotes.Add", resourceCulture);
            }
        }
        
        public static string Text_Repository_Tags {
            get {
                return ResourceManager.GetString("Text.Repository.Tags", resourceCulture);
            }
        }
        
        public static string Text_Repository_Tags_Add {
            get {
                return ResourceManager.GetString("Text.Repository.Tags.Add", resourceCulture);
            }
        }
        
        public static string Text_Repository_Submodules {
            get {
                return ResourceManager.GetString("Text.Repository.Submodules", resourceCulture);
            }
        }
        
        public static string Text_Repository_Submodules_Add {
            get {
                return ResourceManager.GetString("Text.Repository.Submodules.Add", resourceCulture);
            }
        }
        
        public static string Text_Repository_Submodules_Update {
            get {
                return ResourceManager.GetString("Text.Repository.Submodules.Update", resourceCulture);
            }
        }
        
        public static string Text_Repository_Resolve {
            get {
                return ResourceManager.GetString("Text.Repository.Resolve", resourceCulture);
            }
        }
        
        public static string Text_Repository_Continue {
            get {
                return ResourceManager.GetString("Text.Repository.Continue", resourceCulture);
            }
        }
        
        public static string Text_Repository_Abort {
            get {
                return ResourceManager.GetString("Text.Repository.Abort", resourceCulture);
            }
        }
        
        public static string Text_GitFlow {
            get {
                return ResourceManager.GetString("Text.GitFlow", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_Init {
            get {
                return ResourceManager.GetString("Text.GitFlow.Init", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_ProductionBranch {
            get {
                return ResourceManager.GetString("Text.GitFlow.ProductionBranch", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_DevelopBranch {
            get {
                return ResourceManager.GetString("Text.GitFlow.DevelopBranch", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_Feature {
            get {
                return ResourceManager.GetString("Text.GitFlow.Feature", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_Release {
            get {
                return ResourceManager.GetString("Text.GitFlow.Release", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_Hotfix {
            get {
                return ResourceManager.GetString("Text.GitFlow.Hotfix", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_FeaturePrefix {
            get {
                return ResourceManager.GetString("Text.GitFlow.FeaturePrefix", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_ReleasePrefix {
            get {
                return ResourceManager.GetString("Text.GitFlow.ReleasePrefix", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_HotfixPrefix {
            get {
                return ResourceManager.GetString("Text.GitFlow.HotfixPrefix", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_TagPrefix {
            get {
                return ResourceManager.GetString("Text.GitFlow.TagPrefix", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_StartFeature {
            get {
                return ResourceManager.GetString("Text.GitFlow.StartFeature", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_StartRelease {
            get {
                return ResourceManager.GetString("Text.GitFlow.StartRelease", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_StartHotfix {
            get {
                return ResourceManager.GetString("Text.GitFlow.StartHotfix", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_StartFeatureTitle {
            get {
                return ResourceManager.GetString("Text.GitFlow.StartFeatureTitle", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_StartReleaseTitle {
            get {
                return ResourceManager.GetString("Text.GitFlow.StartReleaseTitle", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_StartHotfixTitle {
            get {
                return ResourceManager.GetString("Text.GitFlow.StartHotfixTitle", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_StartPlaceholder {
            get {
                return ResourceManager.GetString("Text.GitFlow.StartPlaceholder", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_FinishFeature {
            get {
                return ResourceManager.GetString("Text.GitFlow.FinishFeature", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_FinishRelease {
            get {
                return ResourceManager.GetString("Text.GitFlow.FinishRelease", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_FinishHotfix {
            get {
                return ResourceManager.GetString("Text.GitFlow.FinishHotfix", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_FinishTarget {
            get {
                return ResourceManager.GetString("Text.GitFlow.FinishTarget", resourceCulture);
            }
        }
        
        public static string Text_GitFlow_KeepBranchAfterFinish {
            get {
                return ResourceManager.GetString("Text.GitFlow.KeepBranchAfterFinish", resourceCulture);
            }
        }
        
        public static string Text_RepoCM_Bookmark {
            get {
                return ResourceManager.GetString("Text.RepoCM.Bookmark", resourceCulture);
            }
        }
        
        public static string Text_RepoCM_Open {
            get {
                return ResourceManager.GetString("Text.RepoCM.Open", resourceCulture);
            }
        }
        
        public static string Text_RepoCM_Explore {
            get {
                return ResourceManager.GetString("Text.RepoCM.Explore", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Push {
            get {
                return ResourceManager.GetString("Text.BranchCM.Push", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_DiscardAll {
            get {
                return ResourceManager.GetString("Text.BranchCM.DiscardAll", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_FastForward {
            get {
                return ResourceManager.GetString("Text.BranchCM.FastForward", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Pull {
            get {
                return ResourceManager.GetString("Text.BranchCM.Pull", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_PullInto {
            get {
                return ResourceManager.GetString("Text.BranchCM.PullInto", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Checkout {
            get {
                return ResourceManager.GetString("Text.BranchCM.Checkout", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Merge {
            get {
                return ResourceManager.GetString("Text.BranchCM.Merge", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Rebase {
            get {
                return ResourceManager.GetString("Text.BranchCM.Rebase", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Finish {
            get {
                return ResourceManager.GetString("Text.BranchCM.Finish", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Rename {
            get {
                return ResourceManager.GetString("Text.BranchCM.Rename", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Delete {
            get {
                return ResourceManager.GetString("Text.BranchCM.Delete", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_Tracking {
            get {
                return ResourceManager.GetString("Text.BranchCM.Tracking", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_CopyName {
            get {
                return ResourceManager.GetString("Text.BranchCM.CopyName", resourceCulture);
            }
        }
        
        public static string Text_BranchCM_UnsetUpstream {
            get {
                return ResourceManager.GetString("Text.BranchCM.UnsetUpstream", resourceCulture);
            }
        }
        
        public static string Text_RemoteCM_Fetch {
            get {
                return ResourceManager.GetString("Text.RemoteCM.Fetch", resourceCulture);
            }
        }
        
        public static string Text_RemoteCM_Prune {
            get {
                return ResourceManager.GetString("Text.RemoteCM.Prune", resourceCulture);
            }
        }
        
        public static string Text_RemoteCM_Prune_Target {
            get {
                return ResourceManager.GetString("Text.RemoteCM.Prune.Target", resourceCulture);
            }
        }
        
        public static string Text_RemoteCM_Edit {
            get {
                return ResourceManager.GetString("Text.RemoteCM.Edit", resourceCulture);
            }
        }
        
        public static string Text_RemoteCM_Delete {
            get {
                return ResourceManager.GetString("Text.RemoteCM.Delete", resourceCulture);
            }
        }
        
        public static string Text_RemoteCM_CopyURL {
            get {
                return ResourceManager.GetString("Text.RemoteCM.CopyURL", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_Reset {
            get {
                return ResourceManager.GetString("Text.CommitCM.Reset", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_Rebase {
            get {
                return ResourceManager.GetString("Text.CommitCM.Rebase", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_CherryPick {
            get {
                return ResourceManager.GetString("Text.CommitCM.CherryPick", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_Reword {
            get {
                return ResourceManager.GetString("Text.CommitCM.Reword", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_Squash {
            get {
                return ResourceManager.GetString("Text.CommitCM.Squash", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_Revert {
            get {
                return ResourceManager.GetString("Text.CommitCM.Revert", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_SaveAsPatch {
            get {
                return ResourceManager.GetString("Text.CommitCM.SaveAsPatch", resourceCulture);
            }
        }
        
        public static string Text_CommitCM_CopySHA {
            get {
                return ResourceManager.GetString("Text.CommitCM.CopySHA", resourceCulture);
            }
        }
        
        public static string Text_TagCM_Push {
            get {
                return ResourceManager.GetString("Text.TagCM.Push", resourceCulture);
            }
        }
        
        public static string Text_TagCM_Delete {
            get {
                return ResourceManager.GetString("Text.TagCM.Delete", resourceCulture);
            }
        }
        
        public static string Text_TagCM_Copy {
            get {
                return ResourceManager.GetString("Text.TagCM.Copy", resourceCulture);
            }
        }
        
        public static string Text_StashCM_Apply {
            get {
                return ResourceManager.GetString("Text.StashCM.Apply", resourceCulture);
            }
        }
        
        public static string Text_StashCM_Pop {
            get {
                return ResourceManager.GetString("Text.StashCM.Pop", resourceCulture);
            }
        }
        
        public static string Text_StashCM_Drop {
            get {
                return ResourceManager.GetString("Text.StashCM.Drop", resourceCulture);
            }
        }
        
        public static string Text_FileCM_Unstage {
            get {
                return ResourceManager.GetString("Text.FileCM.Unstage", resourceCulture);
            }
        }
        
        public static string Text_FileCM_Stage {
            get {
                return ResourceManager.GetString("Text.FileCM.Stage", resourceCulture);
            }
        }
        
        public static string Text_FileCM_Discard {
            get {
                return ResourceManager.GetString("Text.FileCM.Discard", resourceCulture);
            }
        }
        
        public static string Text_FileCM_Stash {
            get {
                return ResourceManager.GetString("Text.FileCM.Stash", resourceCulture);
            }
        }
        
        public static string Text_FileCM_UnstageMulti {
            get {
                return ResourceManager.GetString("Text.FileCM.UnstageMulti", resourceCulture);
            }
        }
        
        public static string Text_FileCM_StageMulti {
            get {
                return ResourceManager.GetString("Text.FileCM.StageMulti", resourceCulture);
            }
        }
        
        public static string Text_FileCM_DiscardMulti {
            get {
                return ResourceManager.GetString("Text.FileCM.DiscardMulti", resourceCulture);
            }
        }
        
        public static string Text_FileCM_StashMulti {
            get {
                return ResourceManager.GetString("Text.FileCM.StashMulti", resourceCulture);
            }
        }
        
        public static string Text_FileCM_SaveAsPatch {
            get {
                return ResourceManager.GetString("Text.FileCM.SaveAsPatch", resourceCulture);
            }
        }
        
        public static string Text_FileCM_AssumeUnchanged {
            get {
                return ResourceManager.GetString("Text.FileCM.AssumeUnchanged", resourceCulture);
            }
        }
        
        public static string Text_FileCM_StageSelectedLines {
            get {
                return ResourceManager.GetString("Text.FileCM.StageSelectedLines", resourceCulture);
            }
        }
        
        public static string Text_FileCM_DiscardSelectedLines {
            get {
                return ResourceManager.GetString("Text.FileCM.DiscardSelectedLines", resourceCulture);
            }
        }
        
        public static string Text_FileCM_UnstageSelectedLines {
            get {
                return ResourceManager.GetString("Text.FileCM.UnstageSelectedLines", resourceCulture);
            }
        }
        
        public static string Text_DeleteBranch {
            get {
                return ResourceManager.GetString("Text.DeleteBranch", resourceCulture);
            }
        }
        
        public static string Text_DeleteBranch_Branch {
            get {
                return ResourceManager.GetString("Text.DeleteBranch.Branch", resourceCulture);
            }
        }
        
        public static string Text_DeleteRemote {
            get {
                return ResourceManager.GetString("Text.DeleteRemote", resourceCulture);
            }
        }
        
        public static string Text_DeleteRemote_Remote {
            get {
                return ResourceManager.GetString("Text.DeleteRemote.Remote", resourceCulture);
            }
        }
        
        public static string Text_DeleteTag {
            get {
                return ResourceManager.GetString("Text.DeleteTag", resourceCulture);
            }
        }
        
        public static string Text_DeleteTag_Tag {
            get {
                return ResourceManager.GetString("Text.DeleteTag.Tag", resourceCulture);
            }
        }
        
        public static string Text_DeleteTag_WithRemote {
            get {
                return ResourceManager.GetString("Text.DeleteTag.WithRemote", resourceCulture);
            }
        }
        
        public static string Text_DeleteSubmodule {
            get {
                return ResourceManager.GetString("Text.DeleteSubmodule", resourceCulture);
            }
        }
        
        public static string Text_DeleteSubmodule_Path {
            get {
                return ResourceManager.GetString("Text.DeleteSubmodule.Path", resourceCulture);
            }
        }
        
        public static string Text_Diff_Next {
            get {
                return ResourceManager.GetString("Text.Diff.Next", resourceCulture);
            }
        }
        
        public static string Text_Diff_Prev {
            get {
                return ResourceManager.GetString("Text.Diff.Prev", resourceCulture);
            }
        }
        
        public static string Text_Diff_SideBySide {
            get {
                return ResourceManager.GetString("Text.Diff.SideBySide", resourceCulture);
            }
        }
        
        public static string Text_Diff_UseMerger {
            get {
                return ResourceManager.GetString("Text.Diff.UseMerger", resourceCulture);
            }
        }
        
        public static string Text_Diff_Welcome {
            get {
                return ResourceManager.GetString("Text.Diff.Welcome", resourceCulture);
            }
        }
        
        public static string Text_Diff_NoChange {
            get {
                return ResourceManager.GetString("Text.Diff.NoChange", resourceCulture);
            }
        }
        
        public static string Text_Diff_Binary {
            get {
                return ResourceManager.GetString("Text.Diff.Binary", resourceCulture);
            }
        }
        
        public static string Text_Diff_Binary_Old {
            get {
                return ResourceManager.GetString("Text.Diff.Binary.Old", resourceCulture);
            }
        }
        
        public static string Text_Diff_Binary_New {
            get {
                return ResourceManager.GetString("Text.Diff.Binary.New", resourceCulture);
            }
        }
        
        public static string Text_Diff_LFS {
            get {
                return ResourceManager.GetString("Text.Diff.LFS", resourceCulture);
            }
        }
        
        public static string Text_Diff_Copy {
            get {
                return ResourceManager.GetString("Text.Diff.Copy", resourceCulture);
            }
        }
        
        public static string Text_Discard {
            get {
                return ResourceManager.GetString("Text.Discard", resourceCulture);
            }
        }
        
        public static string Text_Discard_Changes {
            get {
                return ResourceManager.GetString("Text.Discard.Changes", resourceCulture);
            }
        }
        
        public static string Text_Discard_Warning {
            get {
                return ResourceManager.GetString("Text.Discard.Warning", resourceCulture);
            }
        }
        
        public static string Text_Discard_All {
            get {
                return ResourceManager.GetString("Text.Discard.All", resourceCulture);
            }
        }
        
        public static string Text_Discard_Total {
            get {
                return ResourceManager.GetString("Text.Discard.Total", resourceCulture);
            }
        }
        
        public static string Text_Fetch {
            get {
                return ResourceManager.GetString("Text.Fetch", resourceCulture);
            }
        }
        
        public static string Text_Fetch_Title {
            get {
                return ResourceManager.GetString("Text.Fetch.Title", resourceCulture);
            }
        }
        
        public static string Text_Fetch_Remote {
            get {
                return ResourceManager.GetString("Text.Fetch.Remote", resourceCulture);
            }
        }
        
        public static string Text_Fetch_AllRemotes {
            get {
                return ResourceManager.GetString("Text.Fetch.AllRemotes", resourceCulture);
            }
        }
        
        public static string Text_Fetch_Prune {
            get {
                return ResourceManager.GetString("Text.Fetch.Prune", resourceCulture);
            }
        }
        
        public static string Text_FastForwardWithoutCheck {
            get {
                return ResourceManager.GetString("Text.FastForwardWithoutCheck", resourceCulture);
            }
        }
        
        public static string Text_FileHistory {
            get {
                return ResourceManager.GetString("Text.FileHistory", resourceCulture);
            }
        }
        
        public static string Text_ChangeDisplayMode {
            get {
                return ResourceManager.GetString("Text.ChangeDisplayMode", resourceCulture);
            }
        }
        
        public static string Text_ChangeDisplayMode_Grid {
            get {
                return ResourceManager.GetString("Text.ChangeDisplayMode.Grid", resourceCulture);
            }
        }
        
        public static string Text_ChangeDisplayMode_List {
            get {
                return ResourceManager.GetString("Text.ChangeDisplayMode.List", resourceCulture);
            }
        }
        
        public static string Text_ChangeDisplayMode_Tree {
            get {
                return ResourceManager.GetString("Text.ChangeDisplayMode.Tree", resourceCulture);
            }
        }
        
        public static string Text_Histories {
            get {
                return ResourceManager.GetString("Text.Histories", resourceCulture);
            }
        }
        
        public static string Text_Histories_Search {
            get {
                return ResourceManager.GetString("Text.Histories.Search", resourceCulture);
            }
        }
        
        public static string Text_Histories_SearchClear {
            get {
                return ResourceManager.GetString("Text.Histories.SearchClear", resourceCulture);
            }
        }
        
        public static string Text_Histories_GraphMode {
            get {
                return ResourceManager.GetString("Text.Histories.GraphMode", resourceCulture);
            }
        }
        
        public static string Text_Histories_DisplayMode {
            get {
                return ResourceManager.GetString("Text.Histories.DisplayMode", resourceCulture);
            }
        }
        
        public static string Text_Histories_Selected {
            get {
                return ResourceManager.GetString("Text.Histories.Selected", resourceCulture);
            }
        }
        
        public static string Text_Init {
            get {
                return ResourceManager.GetString("Text.Init", resourceCulture);
            }
        }
        
        public static string Text_Init_Path {
            get {
                return ResourceManager.GetString("Text.Init.Path", resourceCulture);
            }
        }
        
        public static string Text_Init_Tip {
            get {
                return ResourceManager.GetString("Text.Init.Tip", resourceCulture);
            }
        }
        
        public static string Text_Launcher {
            get {
                return ResourceManager.GetString("Text.Launcher", resourceCulture);
            }
        }
        
        public static string Text_Launcher_Menu {
            get {
                return ResourceManager.GetString("Text.Launcher.Menu", resourceCulture);
            }
        }
        
        public static string Text_Launcher_Error {
            get {
                return ResourceManager.GetString("Text.Launcher.Error", resourceCulture);
            }
        }
        
        public static string Text_Launcher_Info {
            get {
                return ResourceManager.GetString("Text.Launcher.Info", resourceCulture);
            }
        }
        
        public static string Text_PageTabBar_New {
            get {
                return ResourceManager.GetString("Text.PageTabBar.New", resourceCulture);
            }
        }
        
        public static string Text_PageTabBar_Welcome_Title {
            get {
                return ResourceManager.GetString("Text.PageTabBar.Welcome.Title", resourceCulture);
            }
        }
        
        public static string Text_PageTabBar_Tab_Close {
            get {
                return ResourceManager.GetString("Text.PageTabBar.Tab.Close", resourceCulture);
            }
        }
        
        public static string Text_PageTabBar_Tab_CloseOther {
            get {
                return ResourceManager.GetString("Text.PageTabBar.Tab.CloseOther", resourceCulture);
            }
        }
        
        public static string Text_PageTabBar_Tab_CloseRight {
            get {
                return ResourceManager.GetString("Text.PageTabBar.Tab.CloseRight", resourceCulture);
            }
        }
        
        public static string Text_PageTabBar_Tab_Bookmark {
            get {
                return ResourceManager.GetString("Text.PageTabBar.Tab.Bookmark", resourceCulture);
            }
        }
        
        public static string Text_PageTabBar_Tab_CopyPath {
            get {
                return ResourceManager.GetString("Text.PageTabBar.Tab.CopyPath", resourceCulture);
            }
        }
        
        public static string Text_Merge {
            get {
                return ResourceManager.GetString("Text.Merge", resourceCulture);
            }
        }
        
        public static string Text_Merge_Source {
            get {
                return ResourceManager.GetString("Text.Merge.Source", resourceCulture);
            }
        }
        
        public static string Text_Merge_Into {
            get {
                return ResourceManager.GetString("Text.Merge.Into", resourceCulture);
            }
        }
        
        public static string Text_Merge_Mode {
            get {
                return ResourceManager.GetString("Text.Merge.Mode", resourceCulture);
            }
        }
        
        public static string Text_Welcome_OpenOrInit {
            get {
                return ResourceManager.GetString("Text.Welcome.OpenOrInit", resourceCulture);
            }
        }
        
        public static string Text_Welcome_OpenTerminal {
            get {
                return ResourceManager.GetString("Text.Welcome.OpenTerminal", resourceCulture);
            }
        }
        
        public static string Text_Welcome_Clone {
            get {
                return ResourceManager.GetString("Text.Welcome.Clone", resourceCulture);
            }
        }
        
        public static string Text_Welcome_Edit {
            get {
                return ResourceManager.GetString("Text.Welcome.Edit", resourceCulture);
            }
        }
        
        public static string Text_Welcome_AddRootFolder {
            get {
                return ResourceManager.GetString("Text.Welcome.AddRootFolder", resourceCulture);
            }
        }
        
        public static string Text_Welcome_AddSubFolder {
            get {
                return ResourceManager.GetString("Text.Welcome.AddSubFolder", resourceCulture);
            }
        }
        
        public static string Text_Welcome_Delete {
            get {
                return ResourceManager.GetString("Text.Welcome.Delete", resourceCulture);
            }
        }
        
        public static string Text_Welcome_Search {
            get {
                return ResourceManager.GetString("Text.Welcome.Search", resourceCulture);
            }
        }
        
        public static string Text_Welcome_Sort {
            get {
                return ResourceManager.GetString("Text.Welcome.Sort", resourceCulture);
            }
        }
        
        public static string Text_Welcome_DragDropTip {
            get {
                return ResourceManager.GetString("Text.Welcome.DragDropTip", resourceCulture);
            }
        }
        
        public static string Text_EditRepositoryNode_TitleForGroup {
            get {
                return ResourceManager.GetString("Text.EditRepositoryNode.TitleForGroup", resourceCulture);
            }
        }
        
        public static string Text_EditRepositoryNode_TitleForRepository {
            get {
                return ResourceManager.GetString("Text.EditRepositoryNode.TitleForRepository", resourceCulture);
            }
        }
        
        public static string Text_EditRepositoryNode_Target {
            get {
                return ResourceManager.GetString("Text.EditRepositoryNode.Target", resourceCulture);
            }
        }
        
        public static string Text_EditRepositoryNode_Name {
            get {
                return ResourceManager.GetString("Text.EditRepositoryNode.Name", resourceCulture);
            }
        }
        
        public static string Text_EditRepositoryNode_Bookmark {
            get {
                return ResourceManager.GetString("Text.EditRepositoryNode.Bookmark", resourceCulture);
            }
        }
        
        public static string Text_DeleteRepositoryNode_TitleForGroup {
            get {
                return ResourceManager.GetString("Text.DeleteRepositoryNode.TitleForGroup", resourceCulture);
            }
        }
        
        public static string Text_DeleteRepositoryNode_TitleForRepository {
            get {
                return ResourceManager.GetString("Text.DeleteRepositoryNode.TitleForRepository", resourceCulture);
            }
        }
        
        public static string Text_DeleteRepositoryNode_Target {
            get {
                return ResourceManager.GetString("Text.DeleteRepositoryNode.Target", resourceCulture);
            }
        }
        
        public static string Text_Pull {
            get {
                return ResourceManager.GetString("Text.Pull", resourceCulture);
            }
        }
        
        public static string Text_Pull_Title {
            get {
                return ResourceManager.GetString("Text.Pull.Title", resourceCulture);
            }
        }
        
        public static string Text_Pull_Remote {
            get {
                return ResourceManager.GetString("Text.Pull.Remote", resourceCulture);
            }
        }
        
        public static string Text_Pull_Branch {
            get {
                return ResourceManager.GetString("Text.Pull.Branch", resourceCulture);
            }
        }
        
        public static string Text_Pull_Into {
            get {
                return ResourceManager.GetString("Text.Pull.Into", resourceCulture);
            }
        }
        
        public static string Text_Pull_UseRebase {
            get {
                return ResourceManager.GetString("Text.Pull.UseRebase", resourceCulture);
            }
        }
        
        public static string Text_Pull_AutoStash {
            get {
                return ResourceManager.GetString("Text.Pull.AutoStash", resourceCulture);
            }
        }
        
        public static string Text_Push {
            get {
                return ResourceManager.GetString("Text.Push", resourceCulture);
            }
        }
        
        public static string Text_Push_Title {
            get {
                return ResourceManager.GetString("Text.Push.Title", resourceCulture);
            }
        }
        
        public static string Text_Push_Local {
            get {
                return ResourceManager.GetString("Text.Push.Local", resourceCulture);
            }
        }
        
        public static string Text_Push_Remote {
            get {
                return ResourceManager.GetString("Text.Push.Remote", resourceCulture);
            }
        }
        
        public static string Text_Push_To {
            get {
                return ResourceManager.GetString("Text.Push.To", resourceCulture);
            }
        }
        
        public static string Text_Push_WithAllTags {
            get {
                return ResourceManager.GetString("Text.Push.WithAllTags", resourceCulture);
            }
        }
        
        public static string Text_Push_Force {
            get {
                return ResourceManager.GetString("Text.Push.Force", resourceCulture);
            }
        }
        
        public static string Text_PushTag {
            get {
                return ResourceManager.GetString("Text.PushTag", resourceCulture);
            }
        }
        
        public static string Text_PushTag_Tag {
            get {
                return ResourceManager.GetString("Text.PushTag.Tag", resourceCulture);
            }
        }
        
        public static string Text_PushTag_Remote {
            get {
                return ResourceManager.GetString("Text.PushTag.Remote", resourceCulture);
            }
        }
        
        public static string Text_Rebase {
            get {
                return ResourceManager.GetString("Text.Rebase", resourceCulture);
            }
        }
        
        public static string Text_Rebase_Target {
            get {
                return ResourceManager.GetString("Text.Rebase.Target", resourceCulture);
            }
        }
        
        public static string Text_Rebase_On {
            get {
                return ResourceManager.GetString("Text.Rebase.On", resourceCulture);
            }
        }
        
        public static string Text_Rebase_AutoStash {
            get {
                return ResourceManager.GetString("Text.Rebase.AutoStash", resourceCulture);
            }
        }
        
        public static string Text_Remote_AddTitle {
            get {
                return ResourceManager.GetString("Text.Remote.AddTitle", resourceCulture);
            }
        }
        
        public static string Text_Remote_EditTitle {
            get {
                return ResourceManager.GetString("Text.Remote.EditTitle", resourceCulture);
            }
        }
        
        public static string Text_Remote_Name {
            get {
                return ResourceManager.GetString("Text.Remote.Name", resourceCulture);
            }
        }
        
        public static string Text_Remote_Name_Placeholder {
            get {
                return ResourceManager.GetString("Text.Remote.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Remote_URL {
            get {
                return ResourceManager.GetString("Text.Remote.URL", resourceCulture);
            }
        }
        
        public static string Text_Remote_URL_Placeholder {
            get {
                return ResourceManager.GetString("Text.Remote.URL.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_RenameBranch {
            get {
                return ResourceManager.GetString("Text.RenameBranch", resourceCulture);
            }
        }
        
        public static string Text_RenameBranch_Target {
            get {
                return ResourceManager.GetString("Text.RenameBranch.Target", resourceCulture);
            }
        }
        
        public static string Text_RenameBranch_Name {
            get {
                return ResourceManager.GetString("Text.RenameBranch.Name", resourceCulture);
            }
        }
        
        public static string Text_RenameBranch_Name_Placeholder {
            get {
                return ResourceManager.GetString("Text.RenameBranch.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Reset {
            get {
                return ResourceManager.GetString("Text.Reset", resourceCulture);
            }
        }
        
        public static string Text_Reset_Target {
            get {
                return ResourceManager.GetString("Text.Reset.Target", resourceCulture);
            }
        }
        
        public static string Text_Reset_MoveTo {
            get {
                return ResourceManager.GetString("Text.Reset.MoveTo", resourceCulture);
            }
        }
        
        public static string Text_Reset_Mode {
            get {
                return ResourceManager.GetString("Text.Reset.Mode", resourceCulture);
            }
        }
        
        public static string Text_Revert {
            get {
                return ResourceManager.GetString("Text.Revert", resourceCulture);
            }
        }
        
        public static string Text_Revert_Commit {
            get {
                return ResourceManager.GetString("Text.Revert.Commit", resourceCulture);
            }
        }
        
        public static string Text_Revert_CommitChanges {
            get {
                return ResourceManager.GetString("Text.Revert.CommitChanges", resourceCulture);
            }
        }
        
        public static string Text_Preference {
            get {
                return ResourceManager.GetString("Text.Preference", resourceCulture);
            }
        }
        
        public static string Text_Preference_General {
            get {
                return ResourceManager.GetString("Text.Preference.General", resourceCulture);
            }
        }
        
        public static string Text_Preference_General_Locale {
            get {
                return ResourceManager.GetString("Text.Preference.General.Locale", resourceCulture);
            }
        }
        
        public static string Text_Preference_General_AvatarServer {
            get {
                return ResourceManager.GetString("Text.Preference.General.AvatarServer", resourceCulture);
            }
        }
        
        public static string Text_Preference_Appearance_Theme {
            get {
                return ResourceManager.GetString("Text.Preference.Appearance.Theme", resourceCulture);
            }
        }
        
        public static string Text_Preference_General_MaxHistoryCommits {
            get {
                return ResourceManager.GetString("Text.Preference.General.MaxHistoryCommits", resourceCulture);
            }
        }
        
        public static string Text_Preference_General_RestoreTabs {
            get {
                return ResourceManager.GetString("Text.Preference.General.RestoreTabs", resourceCulture);
            }
        }
        
        public static string Text_Preference_General_UseFixedTabWidth {
            get {
                return ResourceManager.GetString("Text.Preference.General.UseFixedTabWidth", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git {
            get {
                return ResourceManager.GetString("Text.Preference.Git", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_Path {
            get {
                return ResourceManager.GetString("Text.Preference.Git.Path", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_Version {
            get {
                return ResourceManager.GetString("Text.Preference.Git.Version", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_DefaultCloneDir {
            get {
                return ResourceManager.GetString("Text.Preference.Git.DefaultCloneDir", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_User {
            get {
                return ResourceManager.GetString("Text.Preference.Git.User", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_User_Placeholder {
            get {
                return ResourceManager.GetString("Text.Preference.Git.User.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_Email {
            get {
                return ResourceManager.GetString("Text.Preference.Git.Email", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_Email_Placeholder {
            get {
                return ResourceManager.GetString("Text.Preference.Git.Email.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_CRLF {
            get {
                return ResourceManager.GetString("Text.Preference.Git.CRLF", resourceCulture);
            }
        }
        
        public static string Text_Preference_Git_AutoFetch {
            get {
                return ResourceManager.GetString("Text.Preference.Git.AutoFetch", resourceCulture);
            }
        }
        
        public static string Text_Preference_GPG {
            get {
                return ResourceManager.GetString("Text.Preference.GPG", resourceCulture);
            }
        }
        
        public static string Text_Preference_GPG_Enabled {
            get {
                return ResourceManager.GetString("Text.Preference.GPG.Enabled", resourceCulture);
            }
        }
        
        public static string Text_Preference_GPG_Path {
            get {
                return ResourceManager.GetString("Text.Preference.GPG.Path", resourceCulture);
            }
        }
        
        public static string Text_Preference_GPG_Path_Placeholder {
            get {
                return ResourceManager.GetString("Text.Preference.GPG.Path.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Preference_GPG_UserKey {
            get {
                return ResourceManager.GetString("Text.Preference.GPG.UserKey", resourceCulture);
            }
        }
        
        public static string Text_Preference_GPG_UserKey_Placeholder {
            get {
                return ResourceManager.GetString("Text.Preference.GPG.UserKey.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Preference_Merger {
            get {
                return ResourceManager.GetString("Text.Preference.Merger", resourceCulture);
            }
        }
        
        public static string Text_Preference_Merger_Type {
            get {
                return ResourceManager.GetString("Text.Preference.Merger.Type", resourceCulture);
            }
        }
        
        public static string Text_Preference_Merger_Path {
            get {
                return ResourceManager.GetString("Text.Preference.Merger.Path", resourceCulture);
            }
        }
        
        public static string Text_Preference_Merger_Path_Placeholder {
            get {
                return ResourceManager.GetString("Text.Preference.Merger.Path.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Preference_Merger_CustomMergeCmd {
            get {
                return ResourceManager.GetString("Text.Preference.Merger.CustomMergeCmd", resourceCulture);
            }
        }
        
        public static string Text_Preference_Merger_CustomDiffCmd {
            get {
                return ResourceManager.GetString("Text.Preference.Merger.CustomDiffCmd", resourceCulture);
            }
        }
        
        public static string Text_Stash {
            get {
                return ResourceManager.GetString("Text.Stash", resourceCulture);
            }
        }
        
        public static string Text_Stash_Title {
            get {
                return ResourceManager.GetString("Text.Stash.Title", resourceCulture);
            }
        }
        
        public static string Text_Stash_Message {
            get {
                return ResourceManager.GetString("Text.Stash.Message", resourceCulture);
            }
        }
        
        public static string Text_Stash_Message_Placeholder {
            get {
                return ResourceManager.GetString("Text.Stash.Message.Placeholder", resourceCulture);
            }
        }
        
        public static string Text_Stash_IncludeUntracked {
            get {
                return ResourceManager.GetString("Text.Stash.IncludeUntracked", resourceCulture);
            }
        }
        
        public static string Text_Stashes {
            get {
                return ResourceManager.GetString("Text.Stashes", resourceCulture);
            }
        }
        
        public static string Text_Stashes_Stashes {
            get {
                return ResourceManager.GetString("Text.Stashes.Stashes", resourceCulture);
            }
        }
        
        public static string Text_Stashes_Changes {
            get {
                return ResourceManager.GetString("Text.Stashes.Changes", resourceCulture);
            }
        }
        
        public static string Text_StashDropConfirm {
            get {
                return ResourceManager.GetString("Text.StashDropConfirm", resourceCulture);
            }
        }
        
        public static string Text_StashDropConfirm_Label {
            get {
                return ResourceManager.GetString("Text.StashDropConfirm.Label", resourceCulture);
            }
        }
        
        public static string Text_TwoCommitsDiff {
            get {
                return ResourceManager.GetString("Text.TwoCommitsDiff", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy {
            get {
                return ResourceManager.GetString("Text.WorkingCopy", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Unstaged {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Unstaged", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Unstaged_ViewAssumeUnchaged {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Unstaged.ViewAssumeUnchaged", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Unstaged_Stage {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Unstaged.Stage", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Unstaged_StageAll {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Unstaged.StageAll", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Staged {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Staged", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Staged_Unstage {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Staged.Unstage", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Staged_UnstageAll {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Staged.UnstageAll", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Conflicts {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Conflicts", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_UseTheirs {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.UseTheirs", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_UseMine {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.UseMine", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_OpenMerger {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.OpenMerger", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_CommitMessageTip {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.CommitMessageTip", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_MessageHistories {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.MessageHistories", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Amend {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Amend", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_Commit {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.Commit", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_CommitTip {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.CommitTip", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_CommitAndPush {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.CommitAndPush", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_NoCommitHistories {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.NoCommitHistories", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_HasCommitHistories {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.HasCommitHistories", resourceCulture);
            }
        }
        
        public static string Text_WorkingCopy_IncludeUntracked {
            get {
                return ResourceManager.GetString("Text.WorkingCopy.IncludeUntracked", resourceCulture);
            }
        }
        
        public static string Text_Conflict_Tip {
            get {
                return ResourceManager.GetString("Text.Conflict.Tip", resourceCulture);
            }
        }
        
        public static string Text_ClearStashes {
            get {
                return ResourceManager.GetString("Text.ClearStashes", resourceCulture);
            }
        }
        
        public static string Text_ClearStashes_Message {
            get {
                return ResourceManager.GetString("Text.ClearStashes.Message", resourceCulture);
            }
        }
        
        public static string Text_Reword {
            get {
                return ResourceManager.GetString("Text.Reword", resourceCulture);
            }
        }
        
        public static string Text_Reword_On {
            get {
                return ResourceManager.GetString("Text.Reword.On", resourceCulture);
            }
        }
        
        public static string Text_Reword_Message {
            get {
                return ResourceManager.GetString("Text.Reword.Message", resourceCulture);
            }
        }
        
        public static string Text_Squash {
            get {
                return ResourceManager.GetString("Text.Squash", resourceCulture);
            }
        }
        
        public static string Text_Squash_Head {
            get {
                return ResourceManager.GetString("Text.Squash.Head", resourceCulture);
            }
        }
        
        public static string Text_Squash_To {
            get {
                return ResourceManager.GetString("Text.Squash.To", resourceCulture);
            }
        }
        
        public static string Text_Squash_Message {
            get {
                return ResourceManager.GetString("Text.Squash.Message", resourceCulture);
            }
        }
        
        public static string Text_AssumeUnchanged {
            get {
                return ResourceManager.GetString("Text.AssumeUnchanged", resourceCulture);
            }
        }
        
        public static string Text_AssumeUnchanged_Remove {
            get {
                return ResourceManager.GetString("Text.AssumeUnchanged.Remove", resourceCulture);
            }
        }
        
        public static string Text_AssumeUnchanged_Empty {
            get {
                return ResourceManager.GetString("Text.AssumeUnchanged.Empty", resourceCulture);
            }
        }
        
        public static string Text_Statistics {
            get {
                return ResourceManager.GetString("Text.Statistics", resourceCulture);
            }
        }
        
        public static string Text_Statistics_ThisWeek {
            get {
                return ResourceManager.GetString("Text.Statistics.ThisWeek", resourceCulture);
            }
        }
        
        public static string Text_Statistics_ThisMonth {
            get {
                return ResourceManager.GetString("Text.Statistics.ThisMonth", resourceCulture);
            }
        }
        
        public static string Text_Statistics_ThisYear {
            get {
                return ResourceManager.GetString("Text.Statistics.ThisYear", resourceCulture);
            }
        }
        
        public static string Text_Statistics_TotalCommitters {
            get {
                return ResourceManager.GetString("Text.Statistics.TotalCommitters", resourceCulture);
            }
        }
        
        public static string Text_Statistics_TotalCommits {
            get {
                return ResourceManager.GetString("Text.Statistics.TotalCommits", resourceCulture);
            }
        }
        
        public static string Text_Statistics_Committer {
            get {
                return ResourceManager.GetString("Text.Statistics.Committer", resourceCulture);
            }
        }
        
        public static string Text_Statistics_CommitAmount {
            get {
                return ResourceManager.GetString("Text.Statistics.CommitAmount", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys {
            get {
                return ResourceManager.GetString("Text.Hotkeys", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Global {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Global", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Global_NewTab {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Global.NewTab", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Global_CloseTab {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Global.CloseTab", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Global_GotoNextTab {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Global.GotoNextTab", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Global_CancelPopup {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Global.CancelPopup", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Repo {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Repo", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Repo_ViewHistories {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Repo.ViewHistories", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Repo_ViewChanges {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Repo.ViewChanges", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Repo_ViewStashes {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Repo.ViewStashes", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Repo_ToggleSearch {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Repo.ToggleSearch", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_Repo_StageOrUnstageSelected {
            get {
                return ResourceManager.GetString("Text.Hotkeys.Repo.StageOrUnstageSelected", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_TextEditor {
            get {
                return ResourceManager.GetString("Text.Hotkeys.TextEditor", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_TextEditor_Search {
            get {
                return ResourceManager.GetString("Text.Hotkeys.TextEditor.Search", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_TextEditor_GotoPrevMatch {
            get {
                return ResourceManager.GetString("Text.Hotkeys.TextEditor.GotoPrevMatch", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_TextEditor_GotoNextMatch {
            get {
                return ResourceManager.GetString("Text.Hotkeys.TextEditor.GotoNextMatch", resourceCulture);
            }
        }
        
        public static string Text_Hotkeys_TextEditor_CloseSearch {
            get {
                return ResourceManager.GetString("Text.Hotkeys.TextEditor.CloseSearch", resourceCulture);
            }
        }
        
        public static string Text_NotConfigured {
            get {
                return ResourceManager.GetString("Text.NotConfigured", resourceCulture);
            }
        }
        
        public static string Text_BinaryNotSupported {
            get {
                return ResourceManager.GetString("Text.BinaryNotSupported", resourceCulture);
            }
        }
        
        public static string Text_BlameTypeNotSupported {
            get {
                return ResourceManager.GetString("Text.BlameTypeNotSupported", resourceCulture);
            }
        }
        
        public static string Text_SaveAsPatchSuccess {
            get {
                return ResourceManager.GetString("Text.SaveAsPatchSuccess", resourceCulture);
            }
        }
        
        public static string Text_Cut {
            get {
                return ResourceManager.GetString("Text.Cut", resourceCulture);
            }
        }
        
        public static string Text_Diff_SyntaxHighlight {
            get {
                return ResourceManager.GetString("Text.Diff.SyntaxHighlight", resourceCulture);
            }
        }
        
        public static string Text_Preference_Appearance_DefaultFont {
            get {
                return ResourceManager.GetString("Text.Preference.Appearance.DefaultFont", resourceCulture);
            }
        }
        
        public static string Text_Preference_Appearance_MonospaceFont {
            get {
                return ResourceManager.GetString("Text.Preference.Appearance.MonospaceFont", resourceCulture);
            }
        }
        
        public static string Text_Preference_Appearance_DefaultFontSize {
            get {
                return ResourceManager.GetString("Text.Preference.Appearance.DefaultFontSize", resourceCulture);
            }
        }
        
        public static string Text_Preference_Appearance {
            get {
                return ResourceManager.GetString("Text.Preference.Appearance", resourceCulture);
            }
        }
        
        public static string Text_Repository_OpenWith {
            get {
                return ResourceManager.GetString("Text.Repository.OpenWith", resourceCulture);
            }
        }
        
        public static string Text_SelfUpdate_Title {
            get {
                return ResourceManager.GetString("Text.SelfUpdate.Title", resourceCulture);
            }
        }
        
        public static string Text_SelfUpdate_Error {
            get {
                return ResourceManager.GetString("Text.SelfUpdate.Error", resourceCulture);
            }
        }
        
        public static string Text_SelfUpdate_Available {
            get {
                return ResourceManager.GetString("Text.SelfUpdate.Available", resourceCulture);
            }
        }
        
        public static string Text_SelfUpdate_GotoDownload {
            get {
                return ResourceManager.GetString("Text.SelfUpdate.GotoDownload", resourceCulture);
            }
        }
        
        public static string Text_SelfUpdate_IgnoreThisVersion {
            get {
                return ResourceManager.GetString("Text.SelfUpdate.IgnoreThisVersion", resourceCulture);
            }
        }
        
        public static string Text_SelfUpdate {
            get {
                return ResourceManager.GetString("Text.SelfUpdate", resourceCulture);
            }
        }
        
        public static string Text_SelfUpdate_UpToDate {
            get {
                return ResourceManager.GetString("Text.SelfUpdate.UpToDate", resourceCulture);
            }
        }
        
        public static string Text_Preference_General_Check4UpdatesOnStartup {
            get {
                return ResourceManager.GetString("Text.Preference.General.Check4UpdatesOnStartup", resourceCulture);
            }
        }
    }
}
